'use client';
import { useState, useEffect } from 'react';
import { ArrowUpRight, ArrowRight, CalendarDays, Clock3, MapPin, ShieldCheck, Medal, Shirt, Award, Camera, Gift, CupSoda, Menu, X, Flag, Route, Timer, Check, Sun, Heart } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Registration } from '@/components/registration';
import { PolicyDialog } from '@/components/policies';
const base = process.env.NEXT_PUBLIC_BASE_PATH || '';
export const races = [
 { distance: '5', name: 'Fun Run', fee: 399, level: 'EVERY STEP COUNTS', description: 'Perfect for beginners, students and fitness enthusiasts who want to be part of the tribute run.', features: ['Beginner friendly', 'Run together as a family', 'Finisher medal & certificate'], timed: false },
 { distance: '10', name: 'Challenge Run', fee: 899, level: 'FIND YOUR NEXT GEAR', description: 'Best for regular runners who want to test their endurance and step up to the next level.', features: ['For regular runners', 'Timed BIB included', 'Finisher medal & certificate'], timed: true },
 { distance: '21', name: 'Half Marathon', fee: 899, level: 'GO THE DISTANCE', description: 'Designed for passionate runners who are ready to take on the ultimate tribute challenge.', features: ['For dedicated runners', 'Timed BIB included', 'Finisher medal & certificate'], timed: true },
];
const benefits = [[Shirt,'Official race tee'],[Medal,'Finisher medal'],[Award,'Certificate'],[Sun,'Runner cap'],[CupSoda,'Refreshments'],[Heart,'Energy drink'],[Camera,'Race photographs'],[Gift,'Goodie bag']] as const;
function Countdown() {
 const [left,setLeft] = useState<number | null>(null);
 useEffect(() => { const update = () => setLeft(Math.max(0,new Date('2026-10-04T05:00:00+05:30').getTime()-Date.now())); update(); const t=setInterval(update,1000); return () => clearInterval(t); },[]);
 return <div className="countdown"><span className="countdown-label">THE START LINE AWAITS</span><div>{['DAYS','HRS','MIN','SEC'].map((unit,i) => <div className="time-unit" key={unit}><strong>{left===null?'—':String(Math.floor(left/[86400000,3600000,60000,1000][i])%[10000,24,60,60][i]).padStart(2,'0')}</strong><span>{unit}</span></div>)}</div></div>;
}
export default function Home() {
 const [menu,setMenu]=useState(false);
 const [selected,setSelected]=useState<string|null>(null);
 const [policy,setPolicy]=useState<string|null>(null);
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <div className="topbar"><span><ShieldCheck size={14}/> EXCLUSIVELY FOR AIRWARRIORS & FAMILIES</span><span>AIR FORCE STATION SURATGARH <i/> 2026 EDITION</span></div>
 <header className="site-header"><a className="brand" href="#" aria-label="Sekhon Marathon Suratgarh home"><img src={`${base}/assets/sekhon-logo.png`} alt="Sekhon Indian Air Force Marathon"/><span><b>DESERT BRAVES</b><small>AIR FORCE STATION SURATGARH</small></span></a><nav className={menu?'navigation open':'navigation'} aria-label="Main navigation">{[['The event','#event'],['Race categories','#races'],['Race day','#race-day'],['FAQs','#faqs']].map(([label,href]) => <a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</nav><button className="button nav-cta" onClick={()=>setSelected('10')}>Register now <ArrowUpRight size={17}/></button><button className="menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main">
 <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src={`${base}/assets/desert-braves.webp`} alt="Canvas painting of runners in the Rajasthan desert at sunrise, with Jaguar jets, a Mi-17 V5 and a Mi-35 helicopter in the sky" fetchPriority="high"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light"><span/> INDIAN AIR FORCE TRIBUTE RUN · 2026</div><p className="hero-kicker">SEKHON MARATHON / DESERT BRAVES</p><h1 id="hero-title">THE WINGS<br/>OF <em>COURAGE.</em></h1><p className="hero-subtitle">Run. Soar. Inspire.</p><p className="hero-description">A tribute run honouring Flying Officer<br className="desktop-break"/> Nirmal Jit Singh Sekhon PVC.</p><div className="hero-actions"><button className="button orange" onClick={()=>setSelected('10')}>Find your start line <ArrowUpRight size={20}/></button><a className="text-link light-link" href="#races">Explore the races <ArrowRight size={18}/></a></div><div className="hero-restriction"><ShieldCheck size={16}/> For airwarriors and their families</div></div><div className="hero-location"><span>THE LAND OF SUN AND SAND.</span><b>SURATGARH, RAJASTHAN</b></div></section>
 <section className="event-strip" aria-label="Event essentials"><div><CalendarDays/><span><small>RACE DAY</small><strong>04 October 2026</strong><p>Sunday</p></span></div><div><Clock3/><span><small>EVENT TIME</small><strong>05:00 — 10:00 AM</strong><p>Indian Standard Time</p></span></div><div><MapPin/><span><small>THE START LINE</small><strong>Air Force Station</strong><p>Suratgarh, Rajasthan</p></span></div><div><Flag/><span><small>REGISTRATION CLOSES</small><strong>27 September 2026</strong><p>Choose your distance below</p></span></div></section>
 <section id="races" className="section race-section"><div className="section-heading"><div><div className="eyebrow">01 / CHOOSE YOUR CHALLENGE</div><h2>Your race.<br className="mobile-break"/> Your moment.</h2></div><p>Three distances. One spirit of honour.<br/>Find the start line that’s right for you.</p></div><div className="race-grid">{races.map((race,i)=><article className={`race-card race-${i}`} key={race.distance}><div className="race-top"><span>{race.level}</span>{race.timed&&<span className="timed-tag"><Timer size={13}/> TIMED RUN</span>}</div><div className="race-distance">{race.distance}<span>KM</span></div><h3>{race.name}</h3><p>{race.description}</p><ul>{race.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><div className="race-bottom"><div><strong>₹{race.fee}</strong><span>per participant</span></div><button className="race-select" onClick={()=>setSelected(race.distance)} aria-label={`Register for ${race.distance} kilometre ${race.name}`}><ArrowUpRight size={25}/></button></div></article>)}</div><p className="race-footnote"><Shirt size={16}/> Every registration includes your race tee, medal, certificate and race-day benefits.</p></section>
 <section id="event" className="tribute-section"><div className="tribute-art"><img src={`${base}/assets/desert-braves.webp`} alt="Original Desert Braves canvas artwork inspired by the 2025 Sekhon Marathon" loading="lazy"/><div className="art-caption"><span>RUN, SOAR, INSPIRE</span><strong>More than a finish line.</strong></div></div><div className="tribute-copy"><div className="eyebrow">02 / A LEGACY THAT MOVES US</div><h2>A run inspired by<br/>courage & honour.</h2><p>Sekhon Indian Air Force Marathon 2026 is a tribute run dedicated to the courage, sacrifice and inspiring legacy of Flying Officer Nirmal Jit Singh Sekhon PVC.</p><p>The marathon brings runners together to celebrate fitness, endurance, patriotism and the spirit of honour through multiple race categories at Air Force Station Suratgarh.</p><div className="tribute-stat"><div><strong>1971</strong><span>YEAR OF SACRIFICE</span></div><div><strong>One legacy.</strong><span>COUNTLESS STEPS FORWARD.</span></div></div><a className="text-link" href="#races">Run with pride <ArrowUpRight size={20}/></a></div></section>
 <section className="section benefits-section"><div className="section-heading"><div><div className="eyebrow">INCLUDED WITH REGISTRATION</div><h2>A race day to remember.</h2></div><p>Your race-day benefits,<br/>from the first step to the finish.</p></div><div className="benefits-grid">{benefits.map(([Icon,label])=><div key={label}><Icon size={28} strokeWidth={1.35}/><span>{label}</span></div>)}</div><div className="benefits-note"><Timer size={18}/> Timed BIBs are included exclusively for 10 KM and 21 KM participants.</div></section>
 <section id="race-day" className="race-day-section"><div className="race-day-inner"><div><div className="eyebrow light">03 / KNOW YOUR RACE DAY</div><h2>Arrive ready.<br/>Run with confidence.</h2><p>Sunday, 4 October 2026<br/>05:00 AM – 10:00 AM IST<br/>Air Force Station Suratgarh</p><Countdown/></div><div className="route-panel"><div className="route-title"><Route size={24}/><h3>Your race route</h3></div><Tabs defaultValue="5"><TabsList className="route-tabs">{races.map(r=><TabsTrigger value={r.distance} key={r.distance}>{r.distance} KM</TabsTrigger>)}</TabsList>{races.map(r=><TabsContent value={r.distance} key={r.distance}><div className="route-pending"><MapPin size={36} strokeWidth={1.3}/><span className="status-chip">ROUTE TO BE ANNOUNCED</span><h4>{r.distance} KM · Suratgarh</h4><p>The station route, assembly point and reporting instructions will be shared here once finalised.</p></div></TabsContent>)}</Tabs><div className="route-note"><ShieldCheck size={17}/><p>Entry is restricted to airwarriors and families. Follow station entry instructions and event marshals on race day.</p></div></div></div></section>
 <section id="faqs" className="section faq-section"><div><div className="eyebrow">BEFORE THE START LINE</div><h2>A few things<br/>worth knowing.</h2><p>Everything you need<br/>to plan your participation.</p></div><div className="faq-list">{[
 ['Who can participate?','The Suratgarh event is exclusively for airwarriors and their families. Registration requires email sign-in and the station invitation code shared by the organising team.'],
 ['Which distances can I choose from?','Choose the 5 KM Fun Run for ₹399, the 10 KM Challenge Run for ₹899, or the 21 KM Half Marathon for ₹899. Timed BIBs are included for the 10 KM and 21 KM categories.'],
 ['What is included in my registration?','Your registration includes an official race tee, finisher medal, participation certificate, runner cap, refreshments, energy drink, race photographs and a goodie bag.'],
 ['How does payment confirmation work?','After signing in and entering the station code, complete your participant details. When Suratgarh payment details are available, pay using the station QR code and upload your screenshot with the transaction ID. The organising team verifies payment before confirming your entry.'],
 ['Where can I see the route and reporting instructions?','Suratgarh route maps, assembly points and reporting instructions will be published in the Race day section after they are finalised.'],
 ['When does registration close?','The shared event registration deadline is 27 September 2026. Race day is Sunday, 4 October 2026, from 05:00 AM to 10:00 AM IST.'],
 ].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="closing-banner"><div><div className="eyebrow light">4 OCTOBER 2026 / SURATGARH</div><h2>See you at the start line.</h2><p>Run, soar, inspire. Together.</p></div><button className="button orange" onClick={()=>setSelected('10')}>Choose your race <ArrowUpRight size={21}/></button></section>
 </main><footer><div className="footer-top"><a className="brand footer-brand" href="#"><img src={`${base}/assets/sekhon-logo.png`} alt="Sekhon Marathon"/><span><b>SEKHON MARATHON 2026</b><small>AIR FORCE STATION SURATGARH</small></span></a><p>A tribute marathon celebrating courage,<br/>endurance and the spirit of the Indian Air Force.</p><a className="text-link" href="#race-day">Race-day information <ArrowUpRight size={17}/></a></div><div className="policy-links"><button onClick={()=>setPolicy('terms')}>Terms & Conditions</button><button onClick={()=>setPolicy('privacy')}>Privacy Policy</button><button onClick={()=>setPolicy('refund')}>Refund Policy</button></div><div className="footer-bottom"><span>© 2026 Sekhon Marathon · Suratgarh</span><span>For airwarriors & families</span><span>RUN. SOAR. INSPIRE.</span></div></footer>
 <div className="mobile-register"><span><small>04 OCTOBER · SURATGARH</small><b>Find your start line</b></span><button className="button" onClick={()=>setSelected('10')}>Register <ArrowUpRight size={17}/></button></div>
 {selected && <Registration key={selected} race={selected} onClose={()=>setSelected(null)} onPolicy={setPolicy}/>}
 {policy && <PolicyDialog policy={policy} onClose={()=>setPolicy(null)}/>}
 </>;
}



