'use client';
import { useEffect, useState, useRef, type FormEvent } from 'react';
import { ArrowRight, ArrowLeft, Check, ShieldCheck, LockKeyhole, Mail, UploadCloud, FileCheck2, Info, X, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { supabase, type EventConfig } from '@/lib/supabase';
import type { User } from '@supabase/supabase-js';

const eventId='suratgarh-2026';
const raceNames:Record<string,string>={'5':'Fun Run','10':'Challenge Run','21':'Half Marathon'};
const fees:Record<string,number>={'5':399,'10':899,'21':899};
const blank={full_name:'',mobile:'',dob:'',gender:'',tshirt:'',blood_group:'',emergency_contact:'',city:'Suratgarh',participant_type:'airwarrior',transaction_id:''};
type Details=typeof blank;
function Choice({label,name,value,options,onChange}:{label:string;name:string;value:string;options:(string|{value:string;label:string})[];onChange:(v:string)=>void}) {
 return <div className="form-field"><label htmlFor={name}>{label} <span>*</span></label><Select value={value||null} onValueChange={v=>onChange(v||'')}><SelectTrigger id={name} className="form-select"><SelectValue placeholder="Select an option"/></SelectTrigger><SelectContent>{options.map(o=>{const item=typeof o==='string'?{value:o,label:o}:o;return <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>})}</SelectContent></Select></div>;
}
export function Registration({race,onClose,onPolicy}:{race:string;onClose:()=>void;onPolicy:(p:string)=>void}) {
 const [step,setStep]=useState(0),[chosen,setChosen]=useState(race),[details,setDetails]=useState<Details>(blank),[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[user,setUser]=useState<User|null>(null),[config,setConfig]=useState<EventConfig|null>(null),[checking,setChecking]=useState(true),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[fileUrl,setFileUrl]=useState(''),[consent,setConsent]=useState(false),[result,setResult]=useState<{registration_id:string;payment_status:string}|null>(null),[submissionId,setSubmissionId]=useState('');
 const heading=useRef<HTMLDivElement>(null);
 const [entries,setEntries]=useState<{id:string;full_name:string;race:string;payment_status:string}[]>([]);
 const today=new Date(Date.now()+19800000).toISOString().slice(0,10);
 const active=!!config?.registration_open&&!!config.payment_configured&&new Date(config.registration_deadline)>new Date();
 useEffect(()=>{let pending=crypto.randomUUID();try{pending=sessionStorage.getItem('sekhon-pending-submission')||pending;sessionStorage.setItem('sekhon-pending-submission',pending);}catch{}setSubmissionId(pending); if(!supabase){setChecking(false);return;} let alive=true;const client=supabase; client.from('event_config').select('*').eq('id',eventId).single().then(({data,error:e})=>{if(alive){setConfig(data);setChecking(false);if(e)setError('Registration is temporarily unavailable. Please try again later.');}});client.auth.getSession().then(({data})=>{if(alive)setUser(data.session?.user||null)});const {data:{subscription}}=client.auth.onAuthStateChange((_event,session)=>{if(alive)setUser(session?.user||null)});return()=>{alive=false;subscription.unsubscribe();};},[]);
 useEffect(()=>{if(!file){setFileUrl('');return;}const url=URL.createObjectURL(file);setFileUrl(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{heading.current?.scrollIntoView({block:'nearest'});setError('');},[step]);
 useEffect(()=>{if(!user||!supabase){setEntries([]);return;}let alive=true;supabase.from('registrations').select('id,full_name,race,payment_status').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30).then(({data})=>{if(alive)setEntries(data||[])});return()=>{alive=false;};},[user]);
 const set=(field:keyof Details,v:string)=>setDetails(d=>({...d,[field]:v}));
 async function sendEmail(e:FormEvent){e.preventDefault();if(!supabase||!active)return;setBusy(true);setError('');const {error:e1}=await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{shouldCreateUser:true,emailRedirectTo:window.location.origin+(process.env.NEXT_PUBLIC_BASE_PATH||'')+'/'}});setBusy(false);if(e1)setError('We could not send the sign-in email. Please check the address and try again shortly.');else{setSent(true);setMessage('Check your inbox for the sign-in code. It may take a moment to arrive.');}}
 async function verifyEmail(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const {data,error:e1}=await supabase.auth.verifyOtp({email:email.trim().toLowerCase(),token:otp.trim(),type:'email'});setBusy(false);if(e1)setError('That code is invalid or has expired. Check your email or request a new code.');else{setUser(data.user);setMessage('');}}
 async function redeem(e:FormEvent){e.preventDefault();if(!supabase||!user||!active)return;setBusy(true);setError('');const {data,error:e1}=await supabase.rpc('redeem_invitation',{p_code:code.trim(),p_event_id:eventId});setBusy(false);if(e1||!data?.ok)setError(data?.code==='rate_limited'?'Too many attempts. Please try again later.':'The station code could not be verified. Check it with the organising team.');else{setCode('');setStep(1);}}
 function nextDetails(e:FormEvent){e.preventDefault();if(!details.gender||!details.tshirt||!details.blood_group){setError('Please select your gender, T-shirt size and blood group.');return;}if(details.mobile===details.emergency_contact){setError('Please use another person’s number for the emergency contact.');return;}setStep(2);}
 function selectFile(f:File|undefined){setError('');if(!f)return;if(!['image/jpeg','image/png'].includes(f.type)||f.size>5*1024*1024||f.size===0){setFile(null);setError('Choose a JPG or PNG screenshot, no larger than 5 MB.');return;}setFile(f);}
 async function submit(){if(preview||!supabase||!user||!active||!consent||!file)return;setBusy(true);setError('');try{const body=new FormData();body.set('payload',JSON.stringify({...details,race:chosen,submission_id:submissionId,event_id:eventId,consent:true}));body.set('receipt',file);const {data,error:e1}=await supabase.functions.invoke('submit-registration',{body});if(e1){let explanation='We could not submit your entry. Please retry; your payment should not be repeated.';try{const response=await e1.context?.json();if(response?.error)explanation=response.error;}catch{}throw new Error(explanation);}if(!data?.registration_id)throw new Error('No receipt was returned. Please retry without making another payment.');setResult(data);try{sessionStorage.removeItem('sekhon-pending-submission');}catch{}setStep(4);}catch(e){setError(e instanceof Error?e.message:'Submission failed. Please try again.');}finally{setBusy(false);}}
 const spinner=busy?<LoaderCircle size={17} className="spin"/>:<ArrowRight size={17}/>;
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="registration-dialog"><div ref={heading}><div className="eyebrow">DESERT BRAVES / SEKHON MARATHON 2026</div><DialogTitle>{step===4?'Entry submitted':step===0?'Your start line is here.':step===1?'Tell us about your runner.':step===2?'Complete your payment.':'One last look.'}</DialogTitle><DialogDescription>{step===4?'Your payment is awaiting verification by the organising team.':`4 October 2026 · Air Force Station Suratgarh`}</DialogDescription></div>
 {step<4&&<ol className="registration-steps" aria-label="Registration progress">{['Access','Participant','Payment','Review'].map((label,i)=><li className={i===step?'current':i<step?'complete':''} key={label} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={13}/>:i+1}</span>{label}</li>)}</ol>}
 {preview&&<div className="preview-notice"><Info size={16}/><span>Registration preview · Nothing is saved or submitted.</span></div>}
 {step>0&&step<4&&<div className="selection-summary"><span><b>{chosen} KM</b> {raceNames[chosen]}</span><strong>₹{fees[chosen]}</strong></div>}
 {step===0&&<><RadioGroup value={chosen} onValueChange={v=>setChosen(String(v))} className="registration-races" aria-label="Choose race distance">{Object.keys(raceNames).map(r=><label key={r} className={chosen===r?'selected':''}><RadioGroupItem value={r}/><span><b>{r} KM</b><small>{raceNames[r]}</small></span><strong>₹{fees[r]}</strong></label>)}</RadioGroup>{checking?<div className="notice"><LoaderCircle className="spin"/><p>Checking registration availability…</p></div>:!active?<><div className="notice"><LockKeyhole/><div><b>Registration opens soon</b><p>Station payment details are being finalised. You can explore the registration steps before entries open.</p></div></div><button className="button" onClick={()=>{setPreview(true);setStep(1);}}>Preview registration {spinner}</button></>:!user?<><div className="access-heading"><ShieldCheck size={20}/><p>For airwarriors and families.<br/><span>Sign in with your email, then enter your station code.</span></p></div>{!sent?<form className="registration-form" onSubmit={sendEmail}><div className="form-field"><label htmlFor="signin-email">Email address</label><input id="signin-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254} placeholder="you@example.com"/></div><button className="button" disabled={busy} type="submit">Email me a sign-in code {spinner}</button><p className="privacy-hint"><LockKeyhole size={13}/> Your email is used for registration and event communication.</p></form>:<form className="registration-form" onSubmit={verifyEmail}><div className="form-field"><label htmlFor="email-code">Sign-in code from your email</label><input id="email-code" type="text" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6,10}" value={otp} onChange={e=>setOtp(e.target.value)} required placeholder="Enter the code"/></div><button className="button" disabled={busy} type="submit">Verify email {spinner}</button><button type="button" className="plain-button" onClick={()=>{setSent(false);setOtp('');setMessage('');}}>Change email or request a new code</button></form>}</>:<form className="registration-form" onSubmit={redeem}><div className="signed-in"><Mail size={16}/><span>Signed in as {user.email}</span><button type="button" className="plain-button" onClick={()=>supabase?.auth.signOut()}>Sign out</button></div><div className="form-field"><label htmlFor="station-code">Station invitation code</label><input id="station-code" type="password" autoComplete="off" maxLength={128} value={code} onChange={e=>setCode(e.target.value)} required placeholder="Code shared by the organising team"/><small>Use the code circulated within Air Force Station Suratgarh.</small></div><button className="button" disabled={busy} type="submit">Verify station access {spinner}</button></form>}</>}
 {step===1&&<form className="registration-form" onSubmit={nextDetails}><Choice label="I am registering an" name="participant-type" value={details.participant_type} options={[{value:'airwarrior',label:'Airwarrior'},{value:'family',label:'Family member'}]} onChange={v=>set('participant_type',v)}/><div className="form-grid">{[
 ['full_name','Full name','text','name','Name for the BIB & certificate'],['mobile','Mobile number','tel','tel','10-digit mobile number'],['dob','Date of birth','date','bday',''],['emergency_contact','Emergency contact number','tel','off','Another person’s mobile number'],['city','City','text','address-level2','Your city'],
 ].map(([field,label,type,autocomplete,placeholder])=><div className={`form-field ${field==='full_name'?'wide':''}`} key={field}><label htmlFor={field}>{label} <span>*</span></label><input id={field} value={details[field as keyof Details]} onChange={e=>set(field as keyof Details,e.target.value)} type={type} autoComplete={autocomplete} placeholder={placeholder} required maxLength={type==='tel'?10:100} minLength={field==='full_name'?2:undefined} pattern={type==='tel'?'[6-9][0-9]{9}':undefined} max={type==='date'?today:undefined} min={type==='date'?'1920-01-01':undefined}/></div>)}<Choice label="Gender" name="gender" value={details.gender} options={[{value:'male',label:'Male'},{value:'female',label:'Female'},{value:'other',label:'Other'},{value:'prefer_not_to_say',label:'Prefer not to say'}]} onChange={v=>set('gender',v)}/><Choice label="T-shirt size" name="tshirt" value={details.tshirt} options={['XS','S','M','L','XL','XXL','XXXL']} onChange={v=>set('tshirt',v)}/><Choice label="Blood group" name="blood-group" value={details.blood_group} options={['A+','A-','B+','B-','AB+','AB-','O+','O-','Unknown']} onChange={v=>set('blood_group',v)}/></div><p className="privacy-hint">For a child, a parent or guardian must complete the registration. Eligibility remains subject to station event rules.</p><div className="form-actions"><button type="button" className="plain-button" onClick={()=>setStep(0)}><ArrowLeft size={16}/> Back</button><button type="submit" className="button">Continue to payment <ArrowRight size={17}/></button></div></form>}
 {step===2&&<div className="registration-form">{!preview&&config?.payment_qr_url?<div className="payment-instructions"><img src={config.payment_qr_url} alt="Suratgarh event payment QR code"/><div><span className="eyebrow">PAY THE EXACT AMOUNT</span><strong>₹{fees[chosen]}</strong><p>{config.payee_name}</p><small>{config.upi_id}</small><p>Check the payee in your UPI app before confirming payment.</p></div></div>:<div className="placeholder-payment"><div><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||''}/assets/payment-placeholder.svg`} alt="Non-payment sample QR. Payment details yet to update."/><strong>YET TO UPDATE</strong></div><div><b>Suratgarh payment QR</b><p>Sample only. Payment details are yet to be updated.</p><span>This QR contains a placeholder message and cannot request a payment.</span></div></div>}<div className="form-field"><label htmlFor="transaction-id">Transaction / UTR reference <span>*</span></label><input id="transaction-id" value={details.transaction_id} onChange={e=>set('transaction_id',e.target.value)} autoComplete="off" maxLength={64} placeholder="Reference from your payment app"/></div><label className="upload-zone" htmlFor="receipt"><UploadCloud size={29}/><b>{file?'Replace payment screenshot':'Choose a payment screenshot'}</b><span>JPG or PNG · Up to 5 MB · Visible transaction details</span><input id="receipt" type="file" accept="image/jpeg,image/png" onChange={e=>selectFile(e.target.files?.[0])}/></label>{file&&<div className="uploaded-file"><img src={fileUrl} alt="Your selected payment screenshot"/><span><b>{file.name}</b><small>{(file.size/1024).toFixed(0)} KB · {preview?'Selected for preview only':'Ready for submission'}</small></span><button className="plain-button" aria-label="Remove screenshot" onClick={()=>setFile(null)}><X size={18}/></button></div>}<p className="privacy-hint"><LockKeyhole size={14}/> Payment screenshots are stored privately for verification.</p><div className="form-actions"><button className="plain-button" onClick={()=>setStep(1)}><ArrowLeft size={16}/> Back</button><button className="button" onClick={()=>{if(!preview&&(!file||!/^[A-Za-z0-9-]{6,64}$/.test(details.transaction_id.trim()))){setError('Add a payment screenshot and a valid transaction reference (6–64 letters, digits or hyphens).');return;}setStep(3);}}>Review entry <ArrowRight size={17}/></button></div></div>}
 {step===3&&<div className="registration-form"><dl className="review-details">{[['Participant',details.full_name],['Registering as',details.participant_type==='family'?'Family member':'Airwarrior'],['Mobile',details.mobile],['Email',user?.email||'Email verified before live registration'],['Date of birth',details.dob],['Race',`${chosen} KM · ${raceNames[chosen]}`],['T-shirt',details.tshirt],['Emergency contact',details.emergency_contact],['Amount',`₹${fees[chosen]}`],['Transaction reference',details.transaction_id||'Added during live registration']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="consent-row"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(!!v)}/><label htmlFor="consent">I confirm the participant details are correct, I am authorised to register this participant, and I agree to the <button type="button" onClick={()=>onPolicy('terms')}>Terms & Conditions</button>, <button type="button" onClick={()=>onPolicy('privacy')}>Privacy Policy</button> and <button type="button" onClick={()=>onPolicy('refund')}>Refund Policy</button>.</label></div>{preview&&<div className="notice"><Info/><p>This is the end of the preview. No registration or payment has been submitted.</p></div>}<div className="form-actions"><button className="plain-button" onClick={()=>setStep(2)} disabled={busy}><ArrowLeft size={16}/> Back</button><button className="button" disabled={preview||busy||!consent||!active} onClick={submit}>Submit for verification {spinner}</button></div></div>}
 {step===4&&result&&<div className="submitted"><FileCheck2 size={48}/><span className="status-chip">PAYMENT PENDING REVIEW</span><h3>Thank you, {details.full_name.split(' ')[0]}.</h3><p>Your {chosen} KM registration has been received. The organising team will verify the transaction before confirming your entry.</p><div><small>YOUR REGISTRATION REFERENCE</small><code>{result.registration_id}</code></div><p>Keep this reference and your payment receipt.</p><button className="button" onClick={onClose}>Return to event <ArrowRight size={17}/></button></div>}
 {step===0&&entries.length>0&&<div className="owner-entries"><h3>Your submitted entries</h3>{entries.map(entry=><div key={entry.id}><b>{entry.full_name} · {entry.race} KM</b><span>{entry.payment_status==='verified'?'Payment verified':entry.payment_status==='rejected'?'Payment rejected — contact organisers':'Awaiting payment verification'}</span><code>{entry.id}</code></div>)}</div>} {message&&<p className="form-message" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 </DialogContent></Dialog>;
}


